variable "prefix" {}
variable "lambda_role_arn" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "subnet_az_names" {}
variable "security_group_id" {}
variable "log_group_name" {}
variable "log_stream_name" {}
variable "instance_types" {}
variable "instance_types_az" {}
variable "lambda_rate" {}
variable "use_ec2" {}